### PR TITLE
Improves remaining amount calculation & adds unit test

### PR DESCRIPTION
**Pull request by shahriar-vdc**

### CODE REVIEW

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Test/Unit/Gateway/Command/AbstractCommandTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-magento2-payments/pullRequest?prid=6268168&bid=20406760)

**Review by asbjornu — APPROVED** [review]

**Review by asbjornu — CHANGES_REQUESTED** [review]
Doesn't `php.yml` need to execute `phpunit` somehow for the test to be executed?

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Test/Unit/Gateway/Command/AbstractCommandTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-magento2-payments/pullRequest?prid=6268168&bid=20406760)

**Comment by shahriar-vdc** [comment]
@asbjornu `phpunit` configuration has been added in `php.xml` file in the previous pull request.

**Review by asbjornu — APPROVED** [review]

**Pull request merged**
