### PR TITLE
Adds unit tests for instruments & general improvements

### PR DESCRIPTION
**Pull request by shahriar-vdc**

### CODE REVIEW

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Test/Unit/Model/Instrument/CreditcardTest.php  1
- Test/Unit/Model/Instrument/AbstractInstrumentTest.php  1
- Test/Unit/Model/Instrument/AbstractTestCase.php  1
- Test/Unit/Model/Instrument/SwishTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-magento2-payments/pullRequest?prid=6268124&bid=20406667)

**Review by asbjornu — CHANGES_REQUESTED** [review]
I see no change to the `php.yml` workflow file, is that not required in order to execute these tests?

**Comment by payex-dev** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Test/Unit/Model/Instrument/AbstractInstrumentTest.php  1
- Test/Unit/Model/Instrument/CreditcardTest.php  1
- Test/Unit/Model/Instrument/AbstractTestCase.php  1
- Test/Unit/Model/Instrument/SwishTest.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/swedbank-pay-magento2-payments/pullRequest?prid=6268124&bid=20406667)

**Comment by shahriar-vdc** [comment]
@asbjornu I have updated the workflow file in latest commit. Please check.

**Review by asbjornu — APPROVED** [review]

**Pull request merged**
